### ISSUE TITLE
Add icon to Editor and Game projects

### ISSUE THREAD

**Issue by ChronicallySerious** [sdslabs/Rootex#317]
Add the rootex icon present at `rootex/assets/rootex.ico`

**Comment by IC1101Virgo** [comment]
Is the issue still open? Can i work on this?

**Comment by IronicallySerious** [comment]
@IC1101Virgo Glad to gear youbare interested! This issue is indeed open amd we will be glad to accept this feature. You can read CONTRIBUTING.md to learn about some of our codestyles and the documentation may also help you. 

This piece with likely be in window.cpp which takes in a path and sets the icon, if that is technically possible. Another thing is the editor.app.json and game.app.json may contain an icon file path field which we can use to specify the icon

**Comment by IC1101Virgo** [comment]
@IronicallySerious Thank you 😺 I'll check these out and start working on this :)

**Comment by IronicallySerious** [comment]
Hey @IC1101Virgo have you got an idea about how we can implement this? Wondering if it is better to close this issue if there is no easy way to do this

**Comment by IC1101Virgo** [comment]
Yes sir sure, I had tried this issue till mid of December actually but unfortunately I did not know my way around. You can go ahead and close the issue!
I did give it a go, pardon me I wasn't able to complete it after all 🛩️ 
Thank you!

**Comment by IronicallySerious** [comment]
It's no problem, if we ever need this again we will probably reopen this in the future

**Comment by ChronicallySerious** [comment]
Reopened because we now have a PR for this

**Comment by ChronicallySerious** [comment]
Added in master
