### ISSUE TITLE
PBR rendering

### ISSUE THREAD

**Issue by MadlyFX** [sdslabs/Rootex#428]
Awesome project! Just wondering if there are any plans to move to a PBR rendering pipeline at some point.

**Comment by ChronicallySerious** [comment]
Hello! Thank you for checking us out! 

We do want to have a PBR pipeline going on at some point but right now what we have is probably going to stay that way (unless someone who happens to have a lot of free time lends their help/code).

We have a lot of new stuff on our plate (because we intend to release a game with this in the coming months) as of now and we think PBR is one of those things we'd do after we are done with the critical stuff

**Comment by ChronicallySerious** [comment]
Closing since this is not the focus as of now. (Might reopen if this gets taken further! (It probably will at some day))
